[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600



; Librerías que necesita tu proyecto
lib_deps = 
    adafruit/Adafruit AHTX0@^2.0.0
    adafruit/Adafruit BMP280 Library@^2.6.0
    adafruit/Adafruit Unified Sensor@^1.1.0
    knolleary/PubSubClient@^2.8.0
    bblanchon/ArduinoJson@^6.19.0
    witnessmenow/UniversalTelegramBot @ ^1.3.0  
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    mikaeltulldahl/AsyncOTA@^1.0.2
; Configuración para subir archivos SPIFFS
board_build.filesystem = spiffs

; Habilitar C++17 (necesario para ConnectionHelper)
build_unflags = -std=gnu++11
build_flags = -std=gnu++17